#!/bin/bash
# chkconfig: 2345 20 80
# description: Description comes here....

# Source function library.
. /etc/init.d/functions

start() {
  # code to start app comes here
    /usr/local/bin/thor_svr
}

stop() {
  # code to stop app comes here
    killall -s SIGINT thsvr
}

case "$1" in 
 start)
     start
     ;;
 stop)
     stop
     ;;
 retart)
     stop
     start
     ;;
 *)
      echo "Usage: $0 {start|stop|restart}"
esac

exit 0